/**/bt_executive:
  ros__parameters:
    dock_x: 0.0
    dock_y: 0.0
    dock_yaw: 0.0
    patrol_waypoints: [-2.5, 2.5, 0.0, 2.5, 2.5, -1.5707963, 2.5, -2.5, 3.1415927, -2.5, -2.5, 1.5707963]
/**/battery_sim:
  ros__parameters:
    dock_x: 0.0
    dock_y: 0.0
/**/navsat_transform:
  ros__parameters:
    datum: [33.7756, -84.3963, 0.0]
