/**/bt_executive:
  ros__parameters:
    dock_x: -4.0
    dock_y: -14.0
    dock_yaw: 0.0
    patrol_waypoints: [-1.75, 1.15, -3.1415925, -10.0, 8.0, 2.4486454, 0.0, 8.0, 0.0, 10.0, 8.0, 0.0, 0.0, 0.0, -2.4668517, 0.0, -10.0, -1.5707964]
/**/battery_sim:
  ros__parameters:
    dock_x: -4.0
    dock_y: -14.0
/**/navsat_transform:
  ros__parameters:
    datum: [33.7756, -84.3963, 0.0]
